summon spider ~ ~ ~ {Health:30f,CustomName:'"§f§l[小怪] §7 §l普通蜘蛛"',Attributes:[{Name:"generic.max_health",Base:30d},{Name:"generic.attack_damage",Base:6d}],DeathLootTable:'gen:spider/regular'}
summon creeper ~ ~ ~ {Health:30f,Attributes:[{Name:"generic.max_health",Base:30d}],ExplosionRadius:2b,CustomName:'"§f§l[小怪] §7 §l普通苦力怕"',DeathLootTable:'gen:creeper/regular'}
#{EntityTag:{id:'skeleton',Health:40f,DeathLootTable:'gen:skeleton/advanced',CustomName:'"§f[小怪] §b§l高级小白"',Attributes:[{Name:'generic.max_health',Base:40d}],HandItems:[{id:'bow',Count:1b},{}],HandDropChances:[0f,0f],ArmorItems:[{id:'iron_boots',Count:1b,tag:{Enchantments:[{id:'protection',lvl:1}]}},{id:'iron_leggings',Count:1b,tag:{Enchantments:[{id:'protection',lvl:1}]}},{},{id:'iron_helmet',Count:1b,tag:{Enchantments:[{id:'protection',lvl:1}]}}]},island_egg:1b}"

summon zombie ~ ~ ~ {CustomName:'"§f[小怪] §b§l高跳僵尸"',Health:26f,Attributes:[{Name:'generic.max_health',Base:26d}],ActiveEffects:[{Id:8b,ShowParticles:0b,Duration:99999999,Amplifier:30b}],ArmorDropChances:[0.02f,0f,0f,0f],ArmorItems:[{id:'leather_boots',Count:1b,tag:{display:{Name:'{"text": "轻盈鞋","italic": false}',color:5460948}}},{},{},{}],DeathLootTable:'gen:zombie/high_jumper'}


summon silverfish ~ ~ ~ {CustomName:'"§f§l[小怪] §7 §l普通蠹虫"',Tags:['modified'],Attributes:[{Name:'generic.max_health',Base:18.0d}],Health:18.0f,DeathLootTable:'gen:silverfish/regular'}

summon enderman ~ ~ ~ {AngerTime:200,DeathLootTable:'gen:enderman/advanced',Health:60.0f,CustomName:'"§f§l[小怪]§3§l高级末影人"',Attributes:[{Name:'generic.max_health',Base:60.0d},{Name:'generic.attack_damage',Base:8d}]}

summon villager ~ ~ ~ {Tags:["switch_visible","shopper"],Offers:{Recipes:[{buy:{id:"brick",tag:{coin:1b,CustomModelData:1,display:{Name:'{"text": "银币","italic":false}',Lore:['""','{"text": "十分普通的货币","color": "white","italic": false}']}},Count:30b},sell:{id:"chicken_spawn_egg",Count:1b}},{buy:{id:"brick",tag:{coin:1b,CustomModelData:1,display:{Name:'{"text": "银币","italic":false}',Lore:['""','{"text": "十分普通的货币","color": "white","italic": false}']}},Count:35b},sell:{id:"sheep_spawn_egg",Count:1b}},{buy:{id:"brick",tag:{coin:1b,CustomModelData:1,display:{Name:'{"text": "银币","italic":false}',Lore:['""','{"text": "十分普通的货币","color": "white","italic": false}']}},Count:35b},sell:{id:"cow_spawn_egg",Count:1b}},{buy:{id:"brick",tag:{coin:1b,CustomModelData:1,display:{Name:'{"text": "银币","italic":false}',Lore:['""','{"text": "十分普通的货币","color": "white","italic": false}']}},Count:40b},sell:{id:"pig_spawn_egg",Count:1b}},{buy:{id:"brick",tag:{coin:2b,CustomModelData:2,display:{Name:'{"text": "金币","italic":false,"color":"gold"}',Lore:['""','{"text": "罕见的货币","color": "white","italic": false}']}},Count:3b},sell:{id:"rabbit_spawn_egg",Count:1b}},{buy:{id:"brick",tag:{coin:3b,CustomModelData:3,display:{Name:'{"text": "钻石币","italic":false,"color":"aqua"}',Lore:['""','{"text": "较为珍贵的货币","color": "white","italic": false}']}},Count:1b},sell:{id:"horse_spawn_egg",Count:1b}}]},VillagerData:{profession:"farmer",level:90,type:"plains"},CustomName:'{"text": "动物刷怪蛋商人","color": "#55FF55","bold": true}',CustomNameVisible:1b,Invulnerable:1b,NoAI:1b,Attributes:[{Name:"generic.max_health",Base:1000d}],Health:1000f,ActiveEffects:[{Id:10b,Amplifier:100b,Duration:99999999,ShowParticles:0b}]}


summon zombie ~ ~ ~ {Tags:['modified'],CustomName:'"§f§l[小怪]§d§l专家僵尸"',Attributes:[{Name:'generic.max_health',Base:60d},{Name:'generic.attack_damage',Base:8d}],Health:60f,ArmorDropChances:[0f,0f,0f,0f],ArmorItems:[{id:'iron_boots',Count:1b,tag:{Enchantments:[{id:'minecraft:protection',lvl:2}]}},{id:'iron_leggings',Count:1b,tag:{Enchantments:[{id:'minecraft:protection',lvl:2}]}},{id:'diamond_chestplate',Count:1b,tag:{Enchantments:[{id:'minecraft:protection',lvl:2}]}},{id:'diamond_helmet',Count:1b}],DeathLootTable:'gen:zombie/professional'}

summon skeleton ~ ~ ~ {Tags:['modified'],CustomName:'"§f§l[小怪]§d§l专家僵尸"',Attributes:[{Name:'generic.max_health',Base:60d}],HandDropChances:[0f,0f],HandItems:[{id:"bow",Count:1b},{id:"tipped_arrow",Count:1b,tag:{CustomPotionEffects:[{Id:7b,Amplifier:1b,Duration:1}]}}],Health:60f,ArmorDropChances:[0f,0f,0f,0f],ArmorItems:[{id:'iron_boots',Count:1b,tag:{Enchantments:[{id:'minecraft:protection',lvl:2}]}},{id:'iron_leggings',Count:1b,tag:{Enchantments:[{id:'minecraft:protection',lvl:2}]}},{id:'diamond_chestplate',Count:1b,tag:{Enchantments:[{id:'minecraft:protection',lvl:2}]}},{id:'diamond_helmet',Count:1b}],DeathLootTable:'gen:skeleton/professional'}

give @p carrot_on_a_stick{skill:{trigger:'carrot_stick',id:7s},arrow_left:5b,CustomModelData:4,display:{Name:'{"text": "箭袋","italic": false,"bold": true}',Lore:['""','{"text": "右键从中取出1组箭","color": "white","italic": false}','{"text": "总共保存了5组","color": "white","italic": false}']}}

give @p diamond_sword{skill:{trigger:'shift',id:1s},Damage:761,RepairCost:1000,AttributeModifiers:[{AttributeName:'generic.attack_damage',Amount:10d,Slot:'mainhand',Name:'aword',UUID:[I;-1211018,18461,131317,-36922]}, {AttributeName:'generic.attack_speed',Amount:-2.4d,Slot:'mainhand',Name:'aword',UUID:[I;-12018,-18461,138717,-36922]}],display:{Name:'{"text":"结界之剑","italic":false,"bold":true,"color":"dark_blue"}',Lore:['{"text":"稀有","bold":true,"color":"blue"}','""','{"text":"为了打败怪物，祖先们曾在这处岛屿锻造了","italic":false,"color":"#FFF7CC"}','{"text":"这把结界之剑。","italic":false,"color":"#FFF7CC"}','{"text":"它被祖先遗留在这里，","italic":false,"color":"#FFF7CC"}','{"text":"等待后人的使用。","italic":false,"color":"#FFF7CC"}','""','{"text":"属性：","italic":false,"color":"dark_green"}','{"text":"11 攻击力","italic":false,"color":"dark_green"}','{"text":"耐久无法修复","bold":true,"color":"red"}','""','{"text":"技能：结界","italic":false,"color":"#19FFB2"}','[{"text":"手持本武器","italic":false,"color":"dark_aqua"},{"text":"连按两次","color":"light_purple","bold":true},{"keybind":"key.sneak","color":"light_purple","bold":true},"触发"]','{"text":"在身边5格范围内筑起结界，","italic":false,"color":"dark_aqua"}','{"text":"使其内的怪物每秒","italic":false,"color":"dark_aqua"}','[{"text":"扣除2点生命值","color":"light_purple","italic":false,"bold":true},{"text":"，且获得","bold":false,"color":"dark_aqua"}]','[{"text":"10秒","bold":true,"color":"light_purple","italic":false},{"text":"的","color":"dark_aqua","bold":false},"中毒I",{"text":"效果","color":"dark_aqua","bold":false}]','{"text":"结界维持10秒","italic":false,"color":"#FF33FF"}','{"text":"冷却：2分钟","color":"light_purple","bold":true}']},HideFlags:2}

give @p carrot_on_a_stick{skill:{trigger:"carrot_stick",id:"3s",sid:"dash_gem",Slot:"weapon"},display:{Name:'{"text": "冲刺宝石","color": "gold","italic": false}',Lore:['{"text": "传说","color": "gold"}','""','{"text": "21号程序员有一天想到，如果Ta能够","color": "#ffbdd5","italic": false}','{"text": "世界各地横冲直撞该多好。这份","color": "#ffbdd5","italic": false}','{"text": "梦想渗入了梦界，并最终凝结成这颗宝石。","color": "#ffbdd5","italic": false}','"据说，它包含着概念的力量"','""','{"text": "技能：不知后退","color": "red","bold": true,"italic": false}','[{"keybind":"key.use","color": "white","bold": true,"italic": false},"触发，需要充能"]','{"text": "将本宝石持在主或副手上会自动充能。","color": "yellow","italic": false}','{"text": "充能满时施放技能可以向前冲锋1秒。","color": "yellow","italic": false}','{"text": "期间获得抗性提升II效果，且无法被击退。","color": "yellow","italic": false}','{"text": "冲锋路径上的敌人都将受到伤害。","color": "yellow","italic": false}','{"text": "充能时间：13s","color": "green"}']},Damage:20,HideFlags:127,Enchantments:[{id:"unbreaking",lvl:255}]}

#tellraw @a [{\"text\": \"【结界剑】\"},{\"score\":{\"name\": \"@s\",\"objective\": \"field.c.skill\"}}]

#[{\"text\": \"b\",\"font\": \"island\"},{\"score\":{\"name\": \"@s\",\"objective\": \"cactus.count\"},\"color\": \"yellow\"}]

summon enderman ~ ~ ~ {CustomName:'"§f§l[小怪] §7 §l普通小黑"',DeathLootTable:'gen:enderman/regular',Attributes:[{Name:'generic.attack_damage',Base:7d},{Name:'generic.max_health',Base:35d}],AngerTime:90,id:'minecraft:enderman'}
execute if entity @a[predicate=operation:holding_item_sneak]
#'[{\"text\":\"连按两下\",\"color\":\"white\"},{\"keybind\":\"key.sneak\",\"color\":\"light_purple\",\"bold\":true},\"触发\"]'

#,'[{"text": "持在主手按【","color": "white","italic": false,"bold": true},{"keybind":"key.swapOffhand","color": "light_purple"},"】触发"]'

#'[{"keybind":"key.use","color": "white","bold": true,"italic": false},"触发"]'

#'[{"text": "长按","color": "white","bold": true,"italic": false},{"keybind":"key.use"},"三秒后松开触发"]'

give @s carrot_on_a_stick{skill:{trigger:'carrot_stick',id:4s,sid:'thorn_grass'},display:{Name:'{"text": "荆棘草","color": "dark_purple","italic": false}',Lore:['"史诗"','""','{"text": "人们经常疑问，","color": "#66d472","italic": false}','{"text": "荆棘是如何与仙人掌好上的？这不Minecraft！","color": "#66d472","italic": false}','{"text": ""}','{"text": "然而Ta们所不知道的是，","color": "#66d472","italic": false}','{"text": "荆棘草其实原本是一名神祗的佩剑……","color": "#66d472","italic": false}','""','{"text": "基础属性：","color": "dark_green","italic": false}','{"text": "+5.6 攻击力","color": "dark_green","italic": false}','{"text": "1.7 攻击速度","color": "yellow","italic": false}','{"text": "无法损坏","color": "blue","italic": false}','""','[{"text": "特性：岂曰无","italic": false,"color": "aqua"},{"text": "绿","color": "green"}]','[{"keybind":"key.use","color": "white","bold": true,"italic": false},"触发"]','{"text": "消耗背包中的仙人掌并将其发射","color": "yellow","italic": false}','{"text": "造成3点伤害与随机时长的中毒","color": "yellow","italic": false}','{"text": "消耗：仙人掌","color": "red"}']},AttributeModifiers:[{Name:'ThGrassAttackBoost',Amount:5.6d,AttributeName:'generic.attack_damage',Slot:"mainhand",Operation:0,UUID:[I;-447070937,588990538,-1761490097,429835077]},{Name:'ThGrassASpDecre',AttributeName:'generic.attack_speed',UUID:[I;-1598797219,459948783,-1265214272,26159],Amount:-2.3,Operation:0,Slot:"mainhand"}],Unbreakable:1b,CustomModelData:2}

give @p leather_boots{skill:{trigger:'hold_sneak',id:5s,sid:'boots_de_terra'},RawJSON:{content:'["",{"text":"ຆ","font":"island"}," ",{"score":{"name": "@s","objective": "terra.c.skill"},"color":"yellow"}]',Slot:['boots']},Unbreakable:1b,HideFlags:6,AttributeModifiers:[{Name:'LeatherBootGround',Amount:2.0d,Operation:0,AttributeName:'generic.armor',Slot:"feet",UUID:[I;792867,-11111111,127318725,-98]}],display:{Name:'{"text": "大地之靴","color": "dark_purple","italic": false}',Lore:['"史诗"','""','{"text": "“只要脚触大地，力量就不会断绝”","color": "green","italic": false}','""','{"text": "基础属性：","color": "dark_green","italic": false}','{"text": "+2 护甲","color": "dark_green","italic": false}','{"text": "无法损坏","color": "blue"}','""','{"text": "技能：绝闩","italic": false,"color": "#b5362d","bold": true}','[{"text": "长按","color": "white","bold": true,"italic": false},{"keybind":"key.sneak"},"三秒后松开触发"]','"双手横伸如天平，两脚触地如直木"','{"text": "将承受的所有物理攻击通过身躯传导到脚下的土地里","italic": false,"color": "yellow"}','{"text": "使得自己免疫绝大部分的物理伤害。","italic": false,"color": "yellow"}','{"text": "但但每次承担伤害都会使你的脚越陷越深","italic": false,"color": "yellow"}','{"text": "技能持续时间内受到伤害将减缓你的移度","color": "red","italic": false}','{"text": "限制：若你的移动速度降为0，技能提前结束","color": "red","italic": false}','{"text": "技能持续30秒","color": "green","italic": false}','{"text": "冷却：7分钟","color": "yellow"}']}}


give @p diamond_sword{skill:{trigger:'to_offhand',id:6s,sid:'silver_snow',Slot:"mainhand"},RawJSON:{content:'"null"',Slot:['mainhand']},CustomModelData:1,AttributeModifiers:[{AttributeName:'generic.attack_speed',Amount:-2.0d,Slot:"mainhand",Name:'ice_sword_modifier',Operation:0,UUID:[I;986341,-1738761,738111896,-990031765]},{AttributeName:'generic.attack_damage',Amount:6.1d,UUID:[I;9841,17761,-738111896,-995],Operation:0,Name:'ice_sword_modifier',Slot:"mainhand"}],HideFlags:6,Unbreakable:1b,display:{Name:'{"text": "银雪","color": "dark_purple","italic": false}',Lore:['"史诗"','""','{"text": "传说这是一位住在冰山中的少女","color": "#80ffea","italic": false}','{"text": "剑客的贴身匕首，沾染了","color": "#80ffea","italic": false}','{"text": "万年不散的寒气","color": "#80ffea","italic": false}','""','{"text": "基础属性：","color": "dark_green","italic": false}','{"text": "+6.1 攻击力","color": "dark_green","italic": false}','{"text": "2 攻击速度","color": "yellow","italic": false}','{"text": "无法损坏","color": "blue"}','""','{"text": "特性：","color": "green","italic": false}','[{"text": "站在雪或冰上时，攻速额外","italic": false,"color": "yellow"},{"text": "+0.4","color": "dark_green"}]','""','{"text": "技能：冰霜之心","color": "aqua","italic": false}','[{"text": "持在主手按【","color": "white","italic": false,"bold": true},{"keybind":"key.swapOffhand","color": "light_purple"},"】触发"]','{"text": "使周围的敌人冰冻6秒","color": "#00ffd9","italic": false}','{"text": "特殊生物与Boss可能全部或部分免疫本效果","color": "red"}','{"text": "冷却时间：90秒","color": "yellow"}']}}


give @s leather_boots{skill:{trigger:'auto',Slot:"foot",id:11s,sid:'feather_boots'},RawJSON:{},CustomModelData:2,AttributeModifiers:[{Name:'f_boot_armor',Amount:2.5d,AttributeName:'generic.armor',Operation:0,Slot:"feet",UUID:[I;64827564,-74918764,2468276,-323897456]},{AttributeName:'generic.movement_speed',Name:'fb_speedboost',UUID:[I;128376,-9715412,2938461,298364],Slot:"feet",Amount:0.3,Operation:1}],Enchantments:[{id:"minecraft:feather_falling",lvl:2}],Unbreakable:1b,RepairCost:10000,HideFlags:6,display:{color:784383,Name:'{"text": "羽毛靴","color": "dark_purple","italic": false}',Lore:['"史诗"','""','{"text": "万物之灵飘散于空中形成无色无味，轻盈至极的意志","color": "aqua","italic": false}','{"text": "它们在风的吹拂下慢慢聚集为旋","italic": false,"color": "aqua"}','{"text": "最后沉淀在这皮革制成的轻盈战靴上","color": "aqua","italic": false}','{"text": "“愿风与你同在”","color": "#d6faff"}','""','{"text": "基础属性：","color": "green","italic": false}','{"text": "+2.5 盔甲","italic": false,"color": "dark_green"}','{"text": "+30% 移速","color": "dark_green","italic": false}','""','{"text": "被动：万古云霄","color": "white","bold": true}','{"text": "若你从超过8格的高度摔落，落地前自动获得缓降效果","color": "green"}']}}

give @s netherite_leggings{skill:{trigger:'auto',Slot:'legs',id:12s,sid:'yin_yang'},RawJSON:{},Unbreakable:1b,RepairCost:100000,AttributeModifiers:[{AttributeName:'generic.armor',Amount:8.0d,Name:'yinyang_armor',Slot:"legs",Operation:0,UUID:[I;-396352273,277235367,-1671552473,1024118609]},{UUID:[I;-396352273,277235367,-1671552473,102418609],AttributeName:'generic.armor_toughness',Operation:0,Slot:"legs",Name:'yinyang_art',Amount:3.0d},{Amount:0.1,Operation:1,Name:'yinyang_mh_p',Slot:"legs",AttributeName:'generic.max_health',UUID:[I;-396352273,277235367,-1671552473,1024118600]},{UUID:[I;-396352273,277235367,-1671552473,1024118605],AttributeName:'generic.knockback_resistance',Slot:"legs",Name:'yinyang_kno_rsi',Operation:0,Amount:0.15d}],HideFlags:6,display:{Name:'{"translate": "item.island.yin_yang","color": "gold","italic": false}',Lore:['{"translate": "tier.4"}','""','{"translate": "lore.yin_yang.story.1","color":"white","italic": false}','""','{"translate": "attribute.title"}','[{"text": "+8 ","color": "dark_green","italic": false},{"translate":"attribute.name.generic.armor"}]','[{"text": "+3 ","color": "dark_green","italic": false},{"translate":"attribute.name.generic.armor_toughness"}]','[{"text": "+10% ","color": "dark_green","italic": false},{"translate":"attribute.name.generic.max_health"}]','[{"text": "+1.5 ","color": "dark_green","italic": false},{"translate":"attribute.name.generic.knockback_resistance"}]','""','{"translate":"lore.yin_yang.trait_1.title","italic":false,"color": "gold"}','{"translate":"lore.yin_yang.trait_1.1","italic":false,"color": "gold"}','{"translate":"lore.yin_yang.trait_1.2","italic":false,"color": "gold"}','""','{"translate":"lore.yin_yang.trait_2.title","italic":false,"color": "#d1a3aa"}','{"translate":"lore.yin_yang.trait_2.1","italic":false,"color": "#d1a3aa"}','{"translate":"lore.yin_yang.trait_2.2","italic":false,"color": "#d1a3aa"}','{"translate":"lore.yin_yang.trait_2.3","italic":false,"color": "#d1a3aa"}','{"translate":"lore.yin_yang.trait_2.4","italic":false,"color": "#d1a3aa"}']}}

summon zombie_villager ~ ~ ~ {Tags:["boss","boss_snow"],Attributes:[{Name:'generic.max_health',Base:500.0d}],Health:500f,HandItems:[{id:"iron_sword",Count:1b,tag:{Enchantments:[{id:"sharpness",lvl:3}]}},{}],ArmorItems:[{id:"leather_boots",Count:1b,tag:{display:{color:16777215},Enchantments:[{id:"protection",lvl:3}]}},{id:"leather_leggings",Count:1b,tag:{display:{color:16777215},Enchantments:[{id:"protection",lvl:3}]}},{id:"leather_chestplate",Count:1b,tag:{display:{color:16777215},Enchantments:[{id:"protection",lvl:3}]}},{id:"leather_helmet",tag:{display:{color:16777215},Enchantments:[{id:"protection",lvl:3}]}}],ArmorDropChances:[0f,0f,0f,0f],HandDropChances:[0f,0f],VillagerData:{profession:"minecraft:cleric",type:"snow"}}












